#
# Makefile for the optics drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_MAX86900)		+= max86900.o
obj-$(CONFIG_SENSORS_MAX86902)		+= max86902.o
obj-$(CONFIG_SENSORS_MAX_NOTCHFILTER)	+= max_notchfilter/
obj-$(CONFIG_SENSORS_ADPD142)		+= adpd142.o
obj-$(CONFIG_SENSORS_ADPD143)		+= adpd143.o

obj-$(CONFIG_SENSORS_HRM_ADPD143)	+= hrm_adpd143.o
obj-$(CONFIG_SENSORS_HRMSENSOR)		+= hrmsensor.o
